requests:

  - method: POST
    interval: 60
    repeat: 2
    sleep: 5
    url: http://127.0.0.1:8080
    data:
      - input: label
        key: device
        replace_with: device_sub
      - input: annotation
        key: phone_number
        replace_with: phone_number_sub

  - method: GET
    url: http://127.0.0.1:8080
    interval: 60
    repeat: 4
    data:
      - input: annotation
        key: instance
        replace_with: instance_sub
      - input: label
        key: mountpoint
        replace_with: mountpoint_sub


  - method: TELEGRAM
    interval: 60
    repeat: 3
    api_url: api.telegram.org
    api_token: ""
    chat_id: ""
    data:
      - input: label
        message: "This is a templated messages and this is how you use variables in it: %instance%"
      - input: annotation
        message: "This is another templated messages and this is how you use variables in it: %device%"
