requests:

  - method: POST
    
    url: http://localhost:8080
    data:
      - input: label
        key: device
        replace_with: device_sub
      - input: annotation
        key: phone_number
        replace_with: phone_number_sub

  - method: GET
    url: http://localhost:8080
    data:
      - input: annotation
        key: instance
        replace_with: instance_sub
      - input: label
        key: mountpoint
        replace_with: mountpoint_sub


  - method: TELEGRAM
    api_token: ""
    chat_id: ""
    data:
      - input: label
        message: "This is a templated messages and this is how you use variables in it: %instance%"
      - input: annotation
        message: "This is another templated messages and this is how you use variables in it: %device%"
