version: "3"
services:
  alertmanager:
       restart: always
       build: .
       logging:
         driver: "json-file"
         options:
           max-size: "50mb"
       ports:
           - "8080:8080"
       volumes:
           - config.yml:/app/config.yml
